apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-api
  namespace: fcg
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payments-api
  template:
    metadata:
      labels:
        app: payments-api
    spec:
      containers:
      - name: payments-api
        image: 536765581095.dkr.ecr.us-east-2.amazonaws.com/fcg-payments@sha256:fd3999418b54c92d5b21289eb68ad4b1978482d9cf10db60166902a4178bccee
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_URLS
          value: http://+:8080
        - name: ConnectionStrings__PaymentsDb
          valueFrom:
            configMapKeyRef:
              name: fcg-config
              key: conn-payments
        - name: Jwt__Issuer
          valueFrom:
            configMapKeyRef:
              name: fcg-config
              key: jwt-issuer
        - name: Jwt__Audience
          valueFrom:
            configMapKeyRef:
              name: fcg-config
              key: jwt-audience
        - name: Jwt__Key
          valueFrom:
            secretKeyRef:
              name: fcg-secrets
              key: jwt-key
        - name: GamesApi__BaseUrl
          value: http://games-api
        - name: AWS__Region
          valueFrom:
            configMapKeyRef:
              name: fcg-config
              key: aws-region
        - name: AWS_EC2_METADATA_DISABLED
          value: 'true'
        - name: Queues__PaymentsRequested
          value: https://sqs.us-east-2.amazonaws.com/536765581095/fcg-payments-requested
        - name: Notifications__TopicArn
          value: arn:aws:sns:us-east-2:536765581095:fcg-notifications
        resources:
          requests:
            memory: 256Mi
            cpu: 250m
          limits:
            memory: 512Mi
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: payments-api
  namespace: fcg
spec:
  type: LoadBalancer
  selector:
    app: payments-api
  ports:
  - port: 80
    targetPort: 8080
