apiVersion: v1
kind: ServiceAccount
metadata:
  name: fcg-payments-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::536765581095:role/fcg-payments-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fcg-payments-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "secrets", "configmaps"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fcg-payments-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: fcg-payments-sa
  namespace: default
roleRef:
  kind: Role
  name: fcg-payments-role
  apiGroup: rbac.authorization.k8s.io
